---
title: "5.8_dif_taxa_post intervention"
author: "Ran An"
date: "`r Sys.Date()`"
output: bookdown::gitbook
site: bookdown::bookdown_site
---
##Post intervention-young vs elderly
```{r,warning=FALSE,message=FALSE, echo=FALSE}
library(ggplot2)
library(ggpubr) # add p value
library(dplyr)
library(tibble) # label outliers
library(cowplot)#combine plots
```

Load data into the program
```{r}
#load the relative abundance data
L6 <- read.csv("./input files/biom_GH002_L6.csv", check.names = FALSE, row.names = 1,stringsAsFactors = FALSE,header = TRUE)
L6 <- t(L6)

#load mapping file
meta_p1 <-read.csv("./input files/mapping_GH002.csv",check.names=FALSE, row.names = 1,stringsAsFactors = FALSE, header = TRUE)

# merge the mapping file and L6 data
p6 <- merge(meta_p1,L6, by.x='OTU ID')
colnames(p6)[1:6] # check the quality
p6[] <- lapply(p6, gsub, pattern = "NA", replacement = "0", fixed = TRUE) #change NA to "0"

p6 <- subset(p6, Intervention != "MOCK")   #get rid of mocks
nrow(p6)#check if subset succeed
```

Get the post data, in order to look into age group effects
```{r}
post<-subset(p6, Time == "post")
G1<- rownames(subset(post, Group=="Young"))
G2<- rownames(subset(post, Group=="Elderly"))

post <-t(post)
post<-post[48:271,]
```


```{r, echo=FALSE}
#function for comparison
comparison <- function (dat, G1, G2, p.adjust.method = "BH", sort = FALSE, 
                        paired = FALSE) 
{
  samples <- colnames(dat)
  levels <- rownames(dat)
  M <- matrix(data = NA, length(levels), 1)
  rownames(M) <- levels
  for (i in 1:length(levels)) {
    lvl <- levels[i]
    l.g1 <- dat[lvl, G1]
    l.g2 <- dat[lvl, G2]
    p <- wilcox.test(as.numeric(l.g1), as.numeric(l.g2), 
                     paired = FALSE)$p.value # unpaired for young vs elderly
    M[i, 1] <- p
  }
  if (!is.null(p.adjust.method)) {
    cor.p <- p.adjust(M, method = p.adjust.method)
    names(cor.p) <- rownames(M)
  }
  else {
    cor.p <- as.vector(M)
    names(cor.p) <- rownames(M)
  }
  if (sort) {
    cor.p <- sort(cor.p)
  }
  cor.p
}

result<-comparison(post, G1, G2)
df<-as.data.frame(result)
#df

#write.csv(df, "./tables/dif_taxa_post_pectin_vs_placebo.csv")
```


```{r}
# convert factor to numeric
post <- subset(p6, Time == "post")
nrow(post) # check whether code above worked

# convert factor to numeric
post_1 <- post[,c(1:47)]
post_2 <- post[,c(48:271)]
indx <- sapply(post_2, is.character)
post_2[indx] <- lapply(post_2[indx], function(x) as.numeric(as.character(x)))
post<-cbind(post_1,post_2)
```

Combine multiple plots
```{r}
p <- ggplot(post, aes(x=Group, y=k__Bacteria_p__Firmicutes_c__Clostridia_o__Clostridiales_f__Lachnospiraceae_g__LachnospiraceaeUCG_008, shape = Group))
p <- p + geom_boxplot(outlier.shape=NA)
p <- p + geom_jitter(position=position_jitter(0.2), cex=1.5) + scale_shape_manual(values=c(16,2))
#p <- p + geom_text(aes(label=subject), hjust=-0.5) #add label to "outliers"
p <- p + labs(y="Relative abundance")
p <- p + labs(x="")
#p <- p + theme(axis.title.y = element_text(size = 1))
#p <- p + stat_compare_means(method = "wilcox.test", label.y = 45)
p <- p + theme_classic()
p <- p + theme(legend.position = "none")
p <- p + scale_x_discrete(limits=c("Young","Elderly"))
#p <- p + scale_y_continuous(limits = c(0,0.08), breaks = seq(0,0.1,0.01))
p <- p + ggtitle("Enterorhabdus") + theme(plot.title = element_text(size = 12))


p1 <- ggplot(post, aes(x=Group, y=k__Bacteria_p__Actinobacteria_c__Coriobacteriia_o__Coriobacteriales_f__Coriobacteriaceae_g__uncultured, shape = Group))
p1 <- p1 + geom_boxplot(outlier.shape=NA)
p1 <- p1 + geom_jitter(position=position_jitter(0.2), cex=1.5)+ scale_shape_manual(values=c(16,2))
#p1 <- p1 + geom_text(aes(label=subject), hjust=-0.5) #add label to "outliers"
p1 <- p1 + labs(y="Relative abundance",size=0.4)
p1 <- p1 + labs(x="")
#p <- p + stat_compare_means(method = "wilcox.test", label.y = 45)
p1 <- p1 + theme_classic()
p1 <- p1 + theme(legend.position = "none")
p1 <- p1 + scale_x_discrete(limits=c("Young","Elderly"))
#p1 <- p1 + scale_y_continuous(limits = c(0,0.1),breaks = seq(0,0.1,0.01))
p1 <- p1 + ggtitle("Coriobacteriaceae;g__uncultured") + theme(plot.title = element_text(size = 11))


p2 <- ggplot(post, aes(x=Group, y=k__Bacteria_p__Firmicutes_c__Clostridia_o__Clostridiales_f__FamilyXIII_g__Mogibacterium, shape = Group))
p2 <- p2 + geom_boxplot(outlier.shape=NA)
p2 <- p2 + geom_jitter(position=position_jitter(0.2), cex=1.5)+ scale_shape_manual(values=c(16,2))
#p2 <- p2 + geom_text(aes(label=subject), hjust=-0.5) #add label to "outliers"
p2 <- p2 + labs(y="Relative abundance")
p2 <- p2 + labs(x="")
#p <- p + stat_compare_means(method = "wilcox.test", label.y = 45)
p2 <- p2 + theme_classic()
p2 <- p2 + theme(legend.position = "none")
p2 <- p2 + scale_x_discrete(limits=c("Young","Elderly"))
#p2 <- p2 + scale_y_continuous(limits = c(0,0.04), breaks = seq(0,0.1,0.01))
p2 <- p2 + ggtitle("Mogibacterium") + theme(plot.title = element_text(size = 12))


p3 <- ggplot(post, aes(x=Group, y=k__Bacteria_p__Firmicutes_c__Clostridia_o__Clostridiales_f__Lachnospiraceae_g__LachnospiraceaeUCG_008, shape = Group))
p3 <- p3 + geom_boxplot(outlier.shape=NA)
p3 <- p3 + geom_jitter(position=position_jitter(0.2), cex=1.5)+ scale_shape_manual(values=c(16,2))
#p3 <- p3 + geom_text(aes(label=subject), hjust=-0.5) #add label to "outliers"
p3 <- p3 + labs(y="Relative abundance")
p3 <- p3 + labs(x="")
#p <- p + stat_compare_means(method = "wilcox.test", label.y = 45)
p3 <- p3 + theme_classic()
p3 <- p3 + theme(legend.position = "none")
p3 <- p3 + scale_x_discrete(limits=c("Young","Elderly"))
#p3 <- p3 + scale_y_continuous(limits = c(0,0.006), breaks = seq(0,0.01,0.001))
p3 <- p3 + ggtitle("LachnospiraceaeUCG-008") + theme(plot.title = element_text(size = 12))


plot_grid(p, p1, p2, p3, labels=c("A", "B","C","D"), ncol = 2, nrow = 2)
```
